# Generated by Django 3.2.6 on 2022-04-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220328_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_like',
            field=models.BooleanField(default=1, verbose_name='yêu thích'),
            preserve_default=False,
        ),
    ]
