# Generated by Django 3.2.6 on 2022-04-07 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_auto_20220405_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tên bài viết')),
                ('slug', models.SlugField(max_length=160, verbose_name='blog Slug')),
                ('short_description', models.TextField(verbose_name='Mô tả')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Image sản phẩm')),
                ('is_featured', models.BooleanField(verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
