# Generated by Django 3.2.6 on 2022-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Chờ lấy hàng', 'Chờ lấy hàng'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Trả hàng', 'Trả hàng'), ('Đã hủy', 'Đã hủy')], default='Chờ xác nhận', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
