# Generated by Django 3.2.6 on 2022-04-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Quản lý Địa chỉ', 'verbose_name_plural': 'Quản lý Địa chỉ'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Quản lý Bài viết', 'verbose_name_plural': 'Quản lý Bài viết'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Quản lý Giỏ hàng', 'verbose_name_plural': 'Quản lý Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Quản lý Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Quản lý sản phẩm yêu thích', 'verbose_name_plural': 'Quản lý sản phẩm yêu thích'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Quản lý Đơn hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Quản lý Sản phẩm'},
        ),
    ]
