# Generated by Django 5.1.3 on 2024-11-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220410_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Quản lý sản phẩm yêu thích'},
        ),
    ]
